/*
 * Copyright 2024 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v15.0
processor: MCXN236
package_id: MCXN236VDF
mcu_data: ksdk2_0
processor_version: 0.15.0
pin_labels:
- {pin_num: T4, pin_signal: PIO4_7/CT_INP19, label: RST, identifier: RST}
- {pin_num: N8, pin_signal: PIO4_14/CT4_MAT2/FLEXIO0_D22, label: CS, identifier: CS}
- {pin_num: H3, pin_signal: PIO2_2/WUU0_IN16/CLKOUT/PWM1_A2/FLEXIO0_D10/SAI0_TXD0, label: CAM_XCLK, identifier: CAM_XCLK}
- {pin_num: B14, pin_signal: PIO0_4/WUU0_IN0/EWM0_IN/FC0_P0/FC1_P4/CT0_MAT2/UTICK_CAP2/HSCMP1_OUT/PDM0_CLK, label: CAM_VSYNC, identifier: CAM_VSYNC}
- {pin_num: A14, pin_signal: PIO0_5/EWM0_OUT_b/FC0_P1/FC1_P5/CT0_MAT3/UTICK_CAP3/PDM0_DATA0, label: CAM_HSYNC, identifier: CAM_HSYNC}
- {pin_num: C13, pin_signal: PIO0_7/WUU0_IN1/FC0_P3/CT_INP3, label: CAM_PCLK, identifier: CAM_PCLK}
- {pin_num: D3, pin_signal: PIO1_11/WUU0_IN11/TRACE_DATA3/FC4_P3/CT2_MAT1/FLEXIO0_D19/I3C1_PUR/CAN0_RXD/ADC1_A11, label: CAM_D7, identifier: CAM_D7}
- {pin_num: A4, pin_signal: PIO1_4/WUU0_IN8/FREQME_CLK_IN0/FC3_P4/FC5_P0/CT1_MAT2/FLEXIO0_D12/SAI0_TXD1/ADC0_A20/CMP0_IN2, label: CAM_D7, identifier: CAM_D7;CAM_D0}
- {pin_num: C3, pin_signal: PIO1_10/TRACE_DATA2/FC4_P2/FC5_P6/CT2_MAT0/FLEXIO0_D18/CAN0_TXD/ADC1_A10, label: CAM_D7, identifier: CAM_D7;CAM_D5;CAM_D6}
- {pin_num: B3, pin_signal: PIO1_5/FREQME_CLK_IN1/FC3_P5/FC5_P1/CT1_MAT3/FLEXIO0_D13/SAI0_RXD1/ADC0_A21/CMP0_IN3, label: CAM_D7, identifier: CAM_D7;CAM_D1}
- {pin_num: B1, pin_signal: PIO1_9/TRACE_DATA1/FC4_P1/FC5_P5/CT_INP9/FLEXIO0_D17/I3C1_SCL/ADC1_A9, label: CAM_D7, identifier: CAM_D7;CAM_D4;CAM_D5}
- {pin_num: B2, pin_signal: PIO1_6/TRIG_IN2/FC3_P6/FC5_P2/CT_INP6/FLEXIO0_D14/SAI1_RX_BCLK/CAN1_TXD/ADC0_A22, label: CAM_D7, identifier: CAM_D7;CAM_D2}
- {pin_num: A1, pin_signal: PIO1_8/WUU0_IN10/LPTMR1_ALT3/TRACE_DATA0/FC4_P0/FC5_P4/CT_INP8/FLEXIO0_D16/I3C1_SDA/ADC1_A8, label: CAM_D7, identifier: CAM_D7;CAM_D3;CAM_D4}
- {pin_num: A2, pin_signal: PIO1_7/WUU0_IN9/TRIG_OUT2/FC5_P3/CT_INP7/FLEXIO0_D15/SAI1_RX_FS/CAN1_RXD/ADC0_A23, label: CAM_D7, identifier: CAM_D7;CAM_D3}
- {pin_num: G5, pin_signal: PIO1_19/WUU0_IN15/FREQME_CLK_IN1/FC5_P3/CT3_MAT1/FLEXIO0_D27/CAN0_RXD/ADC1_A19, label: CAM_RST, identifier: CAM_RST}
- {pin_num: G4, pin_signal: PIO1_18/FREQME_CLK_IN0/FC5_P2/FC3_P6/CT3_MAT0/FLEXIO0_D26/CAN0_TXD/ADC1_A18, label: CAM_PDWN, identifier: CAM_PDWN}
- {pin_num: B6, pin_signal: PIO0_24/FC1_P0/CT0_MAT0/ADC0_B16, label: RS, identifier: RS_rev4;RS_revc;RS_revC;RS}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
    LCDFXIOPins_LCD();
    SmartDMACameraPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: B16, peripheral: SWD, signal: SWO, pin_signal: PIO0_2/TDO/SWO/FC1_P2/CT0_MAT0/UTICK_CAP0/I3C0_PUR, slew_rate: fast, open_drain: disable, drive_strength: high,
    pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Enables the clock for PORT0 controller: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port0);

    const port_pin_config_t port0_2_pinB16_config = {/* Internal pull-up/down resistor is disabled */
                                                     kPORT_PullDisable,
                                                     /* Low internal pull resistor value is selected. */
                                                     kPORT_LowPullResistor,
                                                     /* Fast slew rate is configured */
                                                     kPORT_FastSlewRate,
                                                     /* Passive input filter is disabled */
                                                     kPORT_PassiveFilterDisable,
                                                     /* Open drain output is disabled */
                                                     kPORT_OpenDrainDisable,
                                                     /* High drive strength is configured */
                                                     kPORT_HighDriveStrength,
                                                     /* Pin is configured as SWO */
                                                     kPORT_MuxAlt1,
                                                     /* Digital input enabled */
                                                     kPORT_InputBufferEnable,
                                                     /* Digital input is not inverted */
                                                     kPORT_InputNormal,
                                                     /* Pin Control Register fields [15:0] are not locked */
                                                     kPORT_UnlockRegister};
    /* PORT0_2 (pin B16) is configured as SWO */
    PORT_SetPinConfig(PORT0, 2U, &port0_2_pinB16_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
LCDFXIOPins_LCD:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: N8, peripheral: GPIO4, signal: 'GPIO, 14', pin_signal: PIO4_14/CT4_MAT2/FLEXIO0_D22, direction: OUTPUT}
  - {pin_num: B6, peripheral: GPIO0, signal: 'GPIO, 24', pin_signal: PIO0_24/FC1_P0/CT0_MAT0/ADC0_B16, identifier: RS, direction: OUTPUT}
  - {pin_num: R10, peripheral: FLEXIO0, signal: 'D, 27', pin_signal: PIO4_19/TRIG_OUT5/CT3_MAT3/FLEXIO0_D27/ADC0_B1/CMP1_IN4P}
  - {pin_num: T10, peripheral: FLEXIO0, signal: 'D, 28', pin_signal: PIO4_20/TRIG_IN8/FC2_P4/CT2_MAT0/FLEXIO0_D28/ADC1_A6}
  - {pin_num: T4, peripheral: GPIO4, signal: 'GPIO, 7', pin_signal: PIO4_7/CT_INP19, direction: OUTPUT}
  - {pin_num: C8, peripheral: FLEXIO0, signal: 'D, 4', pin_signal: PIO0_20/WUU0_IN4/FC0_P4/FC1_P0/CT_INP0/FLEXIO0_D4/I3C0_SDA/ADC0_A12, drive_strength: high}
  - {pin_num: E11, peripheral: FLEXIO0, signal: 'D, 6', pin_signal: PIO0_14/FC1_P6/FC0_P2/CT_INP2/UTICK_CAP0/FLEXIO0_D6/ADC0_B14}
  - {pin_num: B17, peripheral: FLEXIO0, signal: 'D, 8', pin_signal: PIO3_0/WUU0_IN22/TRIG_IN0/FC7_P3/CT_INP16/PWM0_A0/FLEXIO0_D8}
  - {pin_num: D15, peripheral: FLEXIO0, signal: 'D, 10', pin_signal: PIO3_2/FC7_P0/CT4_MAT0/PWM0_X0/FLEXIO0_D10}
  - {pin_num: K3, peripheral: FLEXIO0, signal: 'D, 12', pin_signal: PIO2_4/WUU0_IN17/PWM1_A1/FLEXIO0_D12/SAI0_RXD1}
  - {pin_num: K2, peripheral: FLEXIO0, signal: 'D, 14', pin_signal: PIO2_6/TRIG_IN4/PWM1_A0/FLEXIO0_D14/SAI0_TX_BCLK}
  - {pin_num: E14, peripheral: FLEXIO0, signal: 'D, 16', pin_signal: PIO3_8/WUU0_IN23/FC6_P4/FC7_P0/CT_INP4/PWM0_A2/FLEXIO0_D16/SAI0_TX_BCLK}
  - {pin_num: F17, peripheral: FLEXIO0, signal: 'D, 18', pin_signal: PIO3_10/FC6_P2/FC7_P4/CT1_MAT0/PWM0_A3/FLEXIO0_D18/SAI0_TXD0}
  - {pin_num: A8, peripheral: FLEXIO0, signal: 'D, 5', pin_signal: PIO0_21/FC0_P5/FC1_P1/CT_INP1/FLEXIO0_D5/I3C0_SCL/ADC0_A13}
  - {pin_num: G13, peripheral: FLEXIO0, signal: 'D, 7', pin_signal: PIO0_15/FC0_P3/CT_INP3/UTICK_CAP1/FLEXIO0_D7/ADC0_B15}
  - {pin_num: C15, peripheral: FLEXIO0, signal: 'D, 9', pin_signal: PIO3_1/TRIG_IN1/FC6_P0/FC7_P6/CT_INP17/PWM0_B0/FLEXIO0_D9/FREQME_CLK_OUT0}
  - {pin_num: J3, peripheral: FLEXIO0, signal: 'D, 11', pin_signal: PIO2_3/PWM1_B2/FLEXIO0_D11/SAI0_RXD0}
  - {pin_num: K1, peripheral: FLEXIO0, signal: 'D, 13', pin_signal: PIO2_5/TRIG_OUT3/PWM1_B1/FLEXIO0_D13/SAI0_TXD1}
  - {pin_num: D14, peripheral: FLEXIO0, signal: 'D, 15', pin_signal: PIO3_7/FC6_P6/FC7_P1/CT4_MAT3/PWM0_B1/FLEXIO0_D15/SAI0_MCLK}
  - {pin_num: F15, peripheral: FLEXIO0, signal: 'D, 17', pin_signal: PIO3_9/FC6_P5/FC7_P2/CT_INP5/PWM0_B2/FLEXIO0_D17/SAI0_TX_FS}
  - {pin_num: F16, peripheral: FLEXIO0, signal: 'D, 19', pin_signal: PIO3_11/WUU0_IN24/FC6_P3/FC7_P5/CT1_MAT1/PWM0_B3/FLEXIO0_D19/SAI0_RXD0}
  - {pin_num: U12, peripheral: GPIO4, signal: 'GPIO, 23', pin_signal: PIO4_23/TRIG_OUT5/FC2_P6/CT2_MAT3/FLEXIO0_D31/ADC0_A2/ADC0_B2/ADC1_B3, direction: INPUT}
  - {pin_num: P1, peripheral: LP_FLEXCOMM2, signal: LPFLEXCOMM_P0, pin_signal: PIO4_0/WUU0_IN18/TRIG_IN6/FC2_P0/CT_INP16/ADC0_A0}
  - {pin_num: P2, peripheral: LP_FLEXCOMM2, signal: LPFLEXCOMM_P1, pin_signal: PIO4_1/TRIG_IN7/FC2_P1/CT_INP17/ADC0_B0}
  - {pin_num: B7, peripheral: GPIO0, signal: 'GPIO, 23', pin_signal: PIO0_23/WUU0_IN5/EWM0_OUT_b/FC1_P3/CT_INP3/FLEXIO0_D7/ADC0_A15, direction: INPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : LCDFXIOPins_LCD
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void LCDFXIOPins_LCD(void)
{
    /* Enables the clock for GPIO0: Enables clock */
    CLOCK_EnableClock(kCLOCK_Gpio0);
    /* Enables the clock for GPIO4: Enables clock */
    CLOCK_EnableClock(kCLOCK_Gpio4);
    /* Enables the clock for PORT0 controller: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port0);
    /* Enables the clock for PORT2: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port2);
    /* Enables the clock for PORT3: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port3);
    /* Enables the clock for PORT4: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port4);

    gpio_pin_config_t gpio0_pinB7_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO0_23 (pin B7)  */
    GPIO_PinInit(GPIO0, 23U, &gpio0_pinB7_config);

    gpio_pin_config_t RS_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO0_24 (pin B6)  */
    GPIO_PinInit(LCDFXIOPINS_LCD_RS_GPIO, LCDFXIOPINS_LCD_RS_PIN, &RS_config);

    gpio_pin_config_t RST_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO4_7 (pin T4)  */
    GPIO_PinInit(LCDFXIOPINS_LCD_RST_GPIO, LCDFXIOPINS_LCD_RST_PIN, &RST_config);

    gpio_pin_config_t CS_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO4_14 (pin N8)  */
    GPIO_PinInit(LCDFXIOPINS_LCD_CS_GPIO, LCDFXIOPINS_LCD_CS_PIN, &CS_config);

    gpio_pin_config_t gpio4_pinU12_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO4_23 (pin U12)  */
    GPIO_PinInit(GPIO4, 23U, &gpio4_pinU12_config);

    /* PORT0_14 (pin E11) is configured as FLEXIO0_D6 */
    PORT_SetPinMux(PORT0, 14U, kPORT_MuxAlt6);

    PORT0->PCR[14] = ((PORT0->PCR[14] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_15 (pin G13) is configured as FLEXIO0_D7 */
    PORT_SetPinMux(PORT0, 15U, kPORT_MuxAlt6);

    PORT0->PCR[15] = ((PORT0->PCR[15] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_20 (pin C8) is configured as FLEXIO0_D4 */
    PORT_SetPinMux(PORT0, 20U, kPORT_MuxAlt6);

    PORT0->PCR[20] = ((PORT0->PCR[20] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_DSE_MASK | PORT_PCR_IBE_MASK)))

                      /* Drive Strength Enable: High. */
                      | PORT_PCR_DSE(PCR_DSE_dse1)

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_21 (pin A8) is configured as FLEXIO0_D5 */
    PORT_SetPinMux(PORT0, 21U, kPORT_MuxAlt6);

    PORT0->PCR[21] = ((PORT0->PCR[21] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_23 (pin B7) is configured as PIO0_23 */
    PORT_SetPinMux(PORT0, 23U, kPORT_MuxAlt0);

    PORT0->PCR[23] = ((PORT0->PCR[23] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_24 (pin B6) is configured as PIO0_24 */
    PORT_SetPinMux(LCDFXIOPINS_LCD_RS_PORT, LCDFXIOPINS_LCD_RS_PIN, kPORT_MuxAlt0);

    PORT0->PCR[24] = ((PORT0->PCR[24] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT2_3 (pin J3) is configured as FLEXIO0_D11 */
    PORT_SetPinMux(PORT2, 3U, kPORT_MuxAlt6);

    PORT2->PCR[3] = ((PORT2->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT2_4 (pin K3) is configured as FLEXIO0_D12 */
    PORT_SetPinMux(PORT2, 4U, kPORT_MuxAlt6);

    PORT2->PCR[4] = ((PORT2->PCR[4] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT2_5 (pin K1) is configured as FLEXIO0_D13 */
    PORT_SetPinMux(PORT2, 5U, kPORT_MuxAlt6);

    PORT2->PCR[5] = ((PORT2->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT2_6 (pin K2) is configured as FLEXIO0_D14 */
    PORT_SetPinMux(PORT2, 6U, kPORT_MuxAlt6);

    PORT2->PCR[6] = ((PORT2->PCR[6] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_0 (pin B17) is configured as FLEXIO0_D8 */
    PORT_SetPinMux(PORT3, 0U, kPORT_MuxAlt6);

    PORT3->PCR[0] = ((PORT3->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_1 (pin C15) is configured as FLEXIO0_D9 */
    PORT_SetPinMux(PORT3, 1U, kPORT_MuxAlt6);

    PORT3->PCR[1] = ((PORT3->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_10 (pin F17) is configured as FLEXIO0_D18 */
    PORT_SetPinMux(PORT3, 10U, kPORT_MuxAlt6);

    PORT3->PCR[10] = ((PORT3->PCR[10] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_11 (pin F16) is configured as FLEXIO0_D19 */
    PORT_SetPinMux(PORT3, 11U, kPORT_MuxAlt6);

    PORT3->PCR[11] = ((PORT3->PCR[11] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_2 (pin D15) is configured as FLEXIO0_D10 */
    PORT_SetPinMux(PORT3, 2U, kPORT_MuxAlt6);

    PORT3->PCR[2] = ((PORT3->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_7 (pin D14) is configured as FLEXIO0_D15 */
    PORT_SetPinMux(PORT3, 7U, kPORT_MuxAlt6);

    PORT3->PCR[7] = ((PORT3->PCR[7] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_8 (pin E14) is configured as FLEXIO0_D16 */
    PORT_SetPinMux(PORT3, 8U, kPORT_MuxAlt6);

    PORT3->PCR[8] = ((PORT3->PCR[8] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_9 (pin F15) is configured as FLEXIO0_D17 */
    PORT_SetPinMux(PORT3, 9U, kPORT_MuxAlt6);

    PORT3->PCR[9] = ((PORT3->PCR[9] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT4_0 (pin P1) is configured as FC2_P0 */
    PORT_SetPinMux(PORT4, 0U, kPORT_MuxAlt2);

    PORT4->PCR[0] = ((PORT4->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT4_1 (pin P2) is configured as FC2_P1 */
    PORT_SetPinMux(PORT4, 1U, kPORT_MuxAlt2);

    PORT4->PCR[1] = ((PORT4->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT4_14 (pin N8) is configured as PIO4_14 */
    PORT_SetPinMux(LCDFXIOPINS_LCD_CS_PORT, LCDFXIOPINS_LCD_CS_PIN, kPORT_MuxAlt0);

    PORT4->PCR[14] = ((PORT4->PCR[14] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT4_19 (pin R10) is configured as FLEXIO0_D27 */
    PORT_SetPinMux(PORT4, 19U, kPORT_MuxAlt6);

    PORT4->PCR[19] = ((PORT4->PCR[19] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT4_20 (pin T10) is configured as FLEXIO0_D28 */
    PORT_SetPinMux(PORT4, 20U, kPORT_MuxAlt6);

    PORT4->PCR[20] = ((PORT4->PCR[20] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT4_23 (pin U12) is configured as PIO4_23 */
    PORT_SetPinMux(PORT4, 23U, kPORT_MuxAlt0);

    PORT4->PCR[23] = ((PORT4->PCR[23] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT4_7 (pin T4) is configured as PIO4_7 */
    PORT_SetPinMux(LCDFXIOPINS_LCD_RST_PORT, LCDFXIOPINS_LCD_RST_PIN, kPORT_MuxAlt0);

    PORT4->PCR[7] = ((PORT4->PCR[7] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
SmartDMACameraPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: H3, peripheral: SCG0, signal: CLKOUT, pin_signal: PIO2_2/WUU0_IN16/CLKOUT/PWM1_A2/FLEXIO0_D10/SAI0_TXD0}
  - {pin_num: B14, peripheral: GPIO0, signal: 'GPIO, 4', pin_signal: PIO0_4/WUU0_IN0/EWM0_IN/FC0_P0/FC1_P4/CT0_MAT2/UTICK_CAP2/HSCMP1_OUT/PDM0_CLK, passive_filter: enable}
  - {pin_num: A14, peripheral: GPIO0, signal: 'GPIO, 5', pin_signal: PIO0_5/EWM0_OUT_b/FC0_P1/FC1_P5/CT0_MAT3/UTICK_CAP3/PDM0_DATA0, passive_filter: enable}
  - {pin_num: C13, peripheral: GPIO0, signal: 'GPIO, 7', pin_signal: PIO0_7/WUU0_IN1/FC0_P3/CT_INP3, slew_rate: slow}
  - {pin_num: D3, peripheral: GPIO1, signal: 'GPIO, 11', pin_signal: PIO1_11/WUU0_IN11/TRACE_DATA3/FC4_P3/CT2_MAT1/FLEXIO0_D19/I3C1_PUR/CAN0_RXD/ADC1_A11}
  - {pin_num: C3, peripheral: GPIO1, signal: 'GPIO, 10', pin_signal: PIO1_10/TRACE_DATA2/FC4_P2/FC5_P6/CT2_MAT0/FLEXIO0_D18/CAN0_TXD/ADC1_A10, identifier: CAM_D6}
  - {pin_num: B1, peripheral: GPIO1, signal: 'GPIO, 9', pin_signal: PIO1_9/TRACE_DATA1/FC4_P1/FC5_P5/CT_INP9/FLEXIO0_D17/I3C1_SCL/ADC1_A9, identifier: CAM_D5}
  - {pin_num: A1, peripheral: GPIO1, signal: 'GPIO, 8', pin_signal: PIO1_8/WUU0_IN10/LPTMR1_ALT3/TRACE_DATA0/FC4_P0/FC5_P4/CT_INP8/FLEXIO0_D16/I3C1_SDA/ADC1_A8, identifier: CAM_D4}
  - {pin_num: A2, peripheral: GPIO1, signal: 'GPIO, 7', pin_signal: PIO1_7/WUU0_IN9/TRIG_OUT2/FC5_P3/CT_INP7/FLEXIO0_D15/SAI1_RX_FS/CAN1_RXD/ADC0_A23, identifier: CAM_D3}
  - {pin_num: B2, peripheral: GPIO1, signal: 'GPIO, 6', pin_signal: PIO1_6/TRIG_IN2/FC3_P6/FC5_P2/CT_INP6/FLEXIO0_D14/SAI1_RX_BCLK/CAN1_TXD/ADC0_A22, identifier: CAM_D2}
  - {pin_num: B3, peripheral: GPIO1, signal: 'GPIO, 5', pin_signal: PIO1_5/FREQME_CLK_IN1/FC3_P5/FC5_P1/CT1_MAT3/FLEXIO0_D13/SAI0_RXD1/ADC0_A21/CMP0_IN3, identifier: CAM_D1}
  - {pin_num: A4, peripheral: GPIO1, signal: 'GPIO, 4', pin_signal: PIO1_4/WUU0_IN8/FREQME_CLK_IN0/FC3_P4/FC5_P0/CT1_MAT2/FLEXIO0_D12/SAI0_TXD1/ADC0_A20/CMP0_IN2,
    identifier: CAM_D0}
  - {pin_num: G4, peripheral: GPIO1, signal: 'GPIO, 18', pin_signal: PIO1_18/FREQME_CLK_IN0/FC5_P2/FC3_P6/CT3_MAT0/FLEXIO0_D26/CAN0_TXD/ADC1_A18, direction: OUTPUT}
  - {pin_num: G5, peripheral: GPIO1, signal: 'GPIO, 19', pin_signal: PIO1_19/WUU0_IN15/FREQME_CLK_IN1/FC5_P3/CT3_MAT1/FLEXIO0_D27/CAN0_RXD/ADC1_A19, direction: OUTPUT,
    gpio_init_state: 'true'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : SmartDMACameraPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void SmartDMACameraPins(void)
{
    /* Enables the clock for GPIO1: Enables clock */
    CLOCK_EnableClock(kCLOCK_Gpio1);
    /* Enables the clock for PORT0 controller: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port0);
    /* Enables the clock for PORT1: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port1);
    /* Enables the clock for PORT2: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port2);

    gpio_pin_config_t CAM_PDWN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_18 (pin G4)  */
    GPIO_PinInit(SMARTDMACAMERAPINS_CAM_PDWN_GPIO, SMARTDMACAMERAPINS_CAM_PDWN_PIN, &CAM_PDWN_config);

    gpio_pin_config_t CAM_RST_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PIO1_19 (pin G5)  */
    GPIO_PinInit(SMARTDMACAMERAPINS_CAM_RST_GPIO, SMARTDMACAMERAPINS_CAM_RST_PIN, &CAM_RST_config);

    /* PORT0_4 (pin B14) is configured as PIO0_4 */
    PORT_SetPinMux(SMARTDMACAMERAPINS_CAM_VSYNC_PORT, SMARTDMACAMERAPINS_CAM_VSYNC_PIN, kPORT_MuxAlt0);

    PORT0->PCR[4] = ((PORT0->PCR[4] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PFE_MASK | PORT_PCR_IBE_MASK)))

                     /* Passive Filter Enable: Enables. */
                     | PORT_PCR_PFE(PCR_PFE_pfe1)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_5 (pin A14) is configured as PIO0_5 */
    PORT_SetPinMux(SMARTDMACAMERAPINS_CAM_HSYNC_PORT, SMARTDMACAMERAPINS_CAM_HSYNC_PIN, kPORT_MuxAlt0);

    PORT0->PCR[5] = ((PORT0->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PFE_MASK | PORT_PCR_IBE_MASK)))

                     /* Passive Filter Enable: Enables. */
                     | PORT_PCR_PFE(PCR_PFE_pfe1)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_7 (pin C13) is configured as PIO0_7 */
    PORT_SetPinMux(SMARTDMACAMERAPINS_CAM_PCLK_PORT, SMARTDMACAMERAPINS_CAM_PCLK_PIN, kPORT_MuxAlt0);

    PORT0->PCR[7] = ((PORT0->PCR[7] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_SRE_MASK | PORT_PCR_IBE_MASK)))

                     /* Slew Rate Enable: Slow. */
                     | PORT_PCR_SRE(PCR_SRE_sre1)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_10 (pin C3) is configured as PIO1_10 */
    PORT_SetPinMux(SMARTDMACAMERAPINS_CAM_D6_PORT, SMARTDMACAMERAPINS_CAM_D6_PIN, kPORT_MuxAlt0);

    PORT1->PCR[10] = ((PORT1->PCR[10] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_11 (pin D3) is configured as PIO1_11 */
    PORT_SetPinMux(SMARTDMACAMERAPINS_CAM_D7_PORT, SMARTDMACAMERAPINS_CAM_D7_PIN, kPORT_MuxAlt0);

    PORT1->PCR[11] = ((PORT1->PCR[11] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_18 (pin G4) is configured as PIO1_18 */
    PORT_SetPinMux(SMARTDMACAMERAPINS_CAM_PDWN_PORT, SMARTDMACAMERAPINS_CAM_PDWN_PIN, kPORT_MuxAlt0);

    PORT1->PCR[18] = ((PORT1->PCR[18] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_19 (pin G5) is configured as PIO1_19 */
    PORT_SetPinMux(SMARTDMACAMERAPINS_CAM_RST_PORT, SMARTDMACAMERAPINS_CAM_RST_PIN, kPORT_MuxAlt0);

    PORT1->PCR[19] = ((PORT1->PCR[19] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_4 (pin A4) is configured as PIO1_4 */
    PORT_SetPinMux(SMARTDMACAMERAPINS_CAM_D0_PORT, SMARTDMACAMERAPINS_CAM_D0_PIN, kPORT_MuxAlt0);

    PORT1->PCR[4] = ((PORT1->PCR[4] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_5 (pin B3) is configured as PIO1_5 */
    PORT_SetPinMux(SMARTDMACAMERAPINS_CAM_D1_PORT, SMARTDMACAMERAPINS_CAM_D1_PIN, kPORT_MuxAlt0);

    PORT1->PCR[5] = ((PORT1->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_6 (pin B2) is configured as PIO1_6 */
    PORT_SetPinMux(SMARTDMACAMERAPINS_CAM_D2_PORT, SMARTDMACAMERAPINS_CAM_D2_PIN, kPORT_MuxAlt0);

    PORT1->PCR[6] = ((PORT1->PCR[6] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_7 (pin A2) is configured as PIO1_7 */
    PORT_SetPinMux(SMARTDMACAMERAPINS_CAM_D3_PORT, SMARTDMACAMERAPINS_CAM_D3_PIN, kPORT_MuxAlt0);

    PORT1->PCR[7] = ((PORT1->PCR[7] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_8 (pin A1) is configured as PIO1_8 */
    PORT_SetPinMux(SMARTDMACAMERAPINS_CAM_D4_PORT, SMARTDMACAMERAPINS_CAM_D4_PIN, kPORT_MuxAlt0);

    PORT1->PCR[8] = ((PORT1->PCR[8] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_9 (pin B1) is configured as PIO1_9 */
    PORT_SetPinMux(SMARTDMACAMERAPINS_CAM_D5_PORT, SMARTDMACAMERAPINS_CAM_D5_PIN, kPORT_MuxAlt0);

    PORT1->PCR[9] = ((PORT1->PCR[9] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT2_2 (pin H3) is configured as CLKOUT */
    PORT_SetPinMux(SMARTDMACAMERAPINS_CAM_XCLK_PORT, SMARTDMACAMERAPINS_CAM_XCLK_PIN, kPORT_MuxAlt1);

    PORT2->PCR[2] = ((PORT2->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
